import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
import Swal from 'sweetalert2';

const userLoginAction = `${process.env.REACT_APP_SERVER_URL}/users/login`;
const initialState = {
  status: 'idle',
  data: '',
}
// Async Login User 
export const loginUserAsync = createAsyncThunk(
  'loginuser',
  async (formData) => {
    var config = {
      method: 'post',
      url: userLoginAction,
      headers: { 
        'Content-Type': 'application/json'
      },
      data : JSON.stringify(formData),
    };
    const response = await axios(config).then((res) => {
      return res.data;
    }).catch(function (error) {
      console.log(error);
    });
    // The value we return becomes the `fulfilled` action payload
    Swal.fire(
      response.title,
      response.message,
      response.type
    );
    return response;
  }
);

export const userLoginSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    updateUser: (state, action) => {
      if(action.payload != undefined){
        state.data = action.payload;
        sessionStorage.setItem('userAccount', JSON.stringify(action.payload));
      }
    },
    userLoggout: (state) => {
      state.data = '';
      sessionStorage.clear();
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loginUserAsync.pending, (state) => {
        console.log('user');
        state.status = 'pending';
      })
      .addCase(loginUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload.user;
        if(action.payload.user){
          sessionStorage.setItem('userAccount', JSON.stringify(action.payload.user));
        }
      })
  }
});

export const { updateUser, userLoggout } = userLoginSlice.actions;

export const userLoginStatus = (state) => state.user.status;
export const userLoginData = (state) => state.user.data;

export default userLoginSlice.reducer;
