import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
import Swal from 'sweetalert2';

const userCreateAction = `${process.env.REACT_APP_SERVER_URL}users/add`;
const userLoginAction = `${process.env.REACT_APP_SERVER_URL}users/login`;
const UserData = {
  user_name: '',
  user_email: '',
  refreshToken: '',
  token: ''
};

const initialState = {
  data: UserData,
  status: 'idle',
};

// Async Create user
export const createUserAsync = createAsyncThunk(
  'user/createUser',
  async (formData) => {
    var config = {
      method: 'post',
      url: userCreateAction,
      headers: { 
        'Content-Type': 'application/json'
      },
      data : JSON.stringify(formData)
    };
    const response = await axios(config).then((res) => {
      return res.data;
    }).catch(function (error) {
      console.log(error);
    });
    // The value we return becomes the `fulfilled` action payload
    Swal.fire(
      response.title,
      response.message,
      response.type
    ); 
    return response;
  }
);

// Async Login User 
export const loginUserAsync = createAsyncThunk(
  'user/createUser',
  async (formData) => {
    var config = {
      method: 'post',
      url: userLoginAction,
      headers: { 
        'Content-Type': 'application/json'
      },
      data : JSON.stringify(formData)
    };
    const response = await axios(config).then((res) => {
      return res.data;
    }).catch(function (error) {
      console.log(error);
    });
    // The value we return becomes the `fulfilled` action payload
    Swal.fire(
      response.title,
      response.message,
      response.type
    );
    return response;
  }
);

export const userSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    updateUser: (state, action) => {
      state.data = action.payload;
    },
    userLoggout: (state) => {
      state.data = UserData;
      sessionStorage.clear();
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createUserAsync.pending, (state) => {
        state.status = 'pending';
      })
      .addCase(createUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
      });
  },
  extraReducers: (builder) => {
    builder
      .addCase(loginUserAsync.pending, (state) => {
        state.status = 'pending';
      })
      .addCase(loginUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload.user;
        if (typeof(Storage) !== "undefined") {
          sessionStorage.setItem('userData', JSON.stringify(action.payload.user));
        } 
      });
    },
});

export const { updateUser, userLoggout } = userSlice.actions;
export const userData = (state) => state.user.data;
export const userStatus = (state) => state.user.status;

export default userSlice.reducer;
