import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { AxiosInstance } from './Instance';

const getUserInforAction = `${process.env.REACT_APP_SERVER_URL}/users/`;

const initialState = {
  data: null,
  status: 'idle',
};

// Async Update user
export const getUserInforAsync = createAsyncThunk(
  'userslice/getUserInfor',
  async () => {
    const response = await AxiosInstance.post(getUserInforAction).then((res) => { return res.data; })
    return response;
  }
);

export const getUserInforSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    removeUserInfor: (state) => {
      state.data = '';
      localStorage.clear();
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getUserInforAsync.pending, (state) => {
        state.status = 'pending';
      })
      .addCase(getUserInforAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload;
      }) 
  }
});

export const { removeUserInfor } = getUserInforSlice.actions;
export const userInformation = (state) => state.user.data;
export const userInformationStatus = (state) => state.user.status;

export default getUserInforSlice.reducer;
